/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include"STM_C6_Driver.h"
#include"STM32F103_C6_GPIO_Driver.h"
#include"STM32F103_C6_EXTI_Driver.h"
#include"STM32F103_C6_UART_Driver.h"
#include"STM32F103_C6_SPI_Driver.h"

uint16_t data;



void clks(void)
{
	ENB_PORTA();
	ENB_AFIO();
	ENB_PORTB();
	ENB_USART1();
}

//void UART_IRQ_CallBack(void)
//{
//	MCAL_UART_RX(USART1, &data, disable);
//	MCAL_UART_TX(USART1, &data, enable);
//}

int main(void)
{
	clks();
	USART_CONFG_t USART1_Cnfg;
	USART1_Cnfg.USART_MODE = USART_MODE_TX_RX;
	USART1_Cnfg.USART_BAUDRATE = USART_BAUDRATE_115200;
	USART1_Cnfg.USART_BITs = USART_BITs_8;
	USART1_Cnfg.USART_HW_FLW_CTL = USART_HwFlowCNTL_NONE;
	USART1_Cnfg.USART_IRQ = USART_IRQ_Enable_None;
	USART1_Cnfg.USART_PARITYBIT = USART_PARITY_NONE;
	USART1_Cnfg.USART_STOPBIT = USART_STOP_BITs_1;
	USART1_Cnfg.P_IRQ_CallBack = NULL;

	MCAL_UART_Init(USART1, &USART1_Cnfg);
	MCAL_UART_GPIO_Init(USART1);

	while(1)
	{
		MCAL_UART_RX(USART1, &data, enable);
		MCAL_UART_TX(USART1, &data, enable);
	}

}
