/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdlib.h>
#include<stdint.h>

//define the Bases
#define RCC_BASE   	0x40021000
#define GPIOA_BASE 	0x40010800
#define INT_BASE	0x40010400
#define AFIO_BASE   0x40010000


// initialize the GPIO
#define GPIOA_ODR   *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRH   *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL	*(volatile uint32_t *)(GPIOA_BASE + 0x00)
//initialize the AFIO
#define AFIO_EXTICR1 	*(volatile uint32_t *)(AFIO_BASE + 0x08)
#define NVIC_EXTI		*(volatile uint32_t *)(0xE000E100)
//initialize the Clock
#define RCC_APB    	*(volatile uint32_t *)(RCC_BASE + 0x18)

//initialize the External INT
#define EXTI_IMR 	*(volatile uint32_t *)(INT_BASE + 0x00)
#define EXTI_RTSR	*(volatile uint32_t *)(INT_BASE + 0x08)
#define EXTI_PR 	*(volatile uint32_t *)(INT_BASE + 0x14)




void clock_init(void){
	//enable clock to AFIO register
	RCC_APB  |= 1<<0;
	//enable clock to I/O Port A
	RCC_APB  |= 1<<2;
}

void GPIO_init(void){
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	GPIOA_CRL |= 1<<2;
}

void AFIO_init(void){
	AFIO_EXTICR1 |= 0;  // enable EXTI0
}


int main(void)
{
	clock_init();

	GPIO_init();

	AFIO_init();

	EXTI_IMR  |= (1<<0); // enable EXTI line 0 mask1

	EXTI_RTSR |= (1<<0); // enable rising trigger

	NVIC_EXTI |= 1<<6;
	while(1);

}


void EXTI0_IRQHandler(void){
	GPIOA_ODR ^= 1<<13;
	EXTI_PR |= (1<<0);
}
